version: '3.8'

volumes:
  html: 
    driver_opts:
      type: cifs
      o: "username=docker,username=yyy,dir_mode=0700,file_mode=0600,uid=1000,gid=1000,mfsymlinks"
      device: "//10.0.0.1/DOCKER/weewx/html"
  config: 
    driver_opts:
      type: cifs
      o: "username=xxx,username=yyy,dir_mode=0700,file_mode=0600,uid=1000,gid=1000,mfsymlinks"
      device: "//10.0.0.1/DOCKER/weewx/config"
  data: 
    driver_opts:
      type: cifs
      o: "username=xxx,username=yyy,dir_mode=0700,file_mode=0600,uid=1000,gid=1000,nobrl,mfsymlinks"
      device: "//10.0.0.1/DOCKER/weewx/data"
  skins: 
    driver_opts:
      type: cifs
      o: "username=xxx,username=yyy,dir_mode=0700,file_mode=0600,uid=1000,gid=1000,mfsymlinks"
      device: "//10.0.0.1/DOCKER/weewx/skins"
  ssl-store:
    driver_opts:
      type: cifs
      o: "username=xxx,username=yyy,dir_mode=0700,file_mode=0600,uid=1000,gid=1000,mfsymlinks"
      device: "//10.0.0.1/DOCKER/ssl-store"

services:
  weewx:
    image: cina/weewx:local
    container_name: weewx
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - ssl-store:/tmp/cert
      - html:/var/www/weewx
      - config:/etc/weewx/config
      - data:/var/lib/weewx
      - skins:/etc/weewx/skins
    ports:
      - 8100:8100
    restart: unless-stopped
    tty: true

  webserver:
    image: pierrezemb/gostatic
    container_name: webserver
    volumes:
      - html:/srv/http
    ports:
      - 8043:8043
    user: 1000:1000
    restart: unless-stopped
